// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package OAuth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OAuthClient is the client API for OAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAuthClient interface {
	RequestAccessTokens(ctx context.Context, in *AuthorizationGrant, opts ...grpc.CallOption) (*AccessTokens, error)
	RefreshAccessTokens(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*AccessTokens, error)
	InvalidateTokens(ctx context.Context, in *LogoutToken, opts ...grpc.CallOption) (*Response, error)
	OAuthTest(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*Response, error)
	PersistUser(ctx context.Context, in *EmailCode, opts ...grpc.CallOption) (*Response, error)
	CreateTempUser(ctx context.Context, in *UserForm, opts ...grpc.CallOption) (*Response, error)
}

type oAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthClient(cc grpc.ClientConnInterface) OAuthClient {
	return &oAuthClient{cc}
}

func (c *oAuthClient) RequestAccessTokens(ctx context.Context, in *AuthorizationGrant, opts ...grpc.CallOption) (*AccessTokens, error) {
	out := new(AccessTokens)
	err := c.cc.Invoke(ctx, "/OAuth.OAuth/RequestAccessTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClient) RefreshAccessTokens(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*AccessTokens, error) {
	out := new(AccessTokens)
	err := c.cc.Invoke(ctx, "/OAuth.OAuth/RefreshAccessTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClient) InvalidateTokens(ctx context.Context, in *LogoutToken, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/OAuth.OAuth/InvalidateTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClient) OAuthTest(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/OAuth.OAuth/OAuthTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClient) PersistUser(ctx context.Context, in *EmailCode, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/OAuth.OAuth/PersistUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClient) CreateTempUser(ctx context.Context, in *UserForm, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/OAuth.OAuth/CreateTempUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthServer is the server API for OAuth service.
// All implementations must embed UnimplementedOAuthServer
// for forward compatibility
type OAuthServer interface {
	RequestAccessTokens(context.Context, *AuthorizationGrant) (*AccessTokens, error)
	RefreshAccessTokens(context.Context, *AccessTokenRequest) (*AccessTokens, error)
	InvalidateTokens(context.Context, *LogoutToken) (*Response, error)
	OAuthTest(context.Context, *TestMessage) (*Response, error)
	PersistUser(context.Context, *EmailCode) (*Response, error)
	CreateTempUser(context.Context, *UserForm) (*Response, error)
	mustEmbedUnimplementedOAuthServer()
}

// UnimplementedOAuthServer must be embedded to have forward compatible implementations.
type UnimplementedOAuthServer struct {
}

func (UnimplementedOAuthServer) RequestAccessTokens(context.Context, *AuthorizationGrant) (*AccessTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAccessTokens not implemented")
}
func (UnimplementedOAuthServer) RefreshAccessTokens(context.Context, *AccessTokenRequest) (*AccessTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshAccessTokens not implemented")
}
func (UnimplementedOAuthServer) InvalidateTokens(context.Context, *LogoutToken) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateTokens not implemented")
}
func (UnimplementedOAuthServer) OAuthTest(context.Context, *TestMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OAuthTest not implemented")
}
func (UnimplementedOAuthServer) PersistUser(context.Context, *EmailCode) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersistUser not implemented")
}
func (UnimplementedOAuthServer) CreateTempUser(context.Context, *UserForm) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTempUser not implemented")
}
func (UnimplementedOAuthServer) mustEmbedUnimplementedOAuthServer() {}

// UnsafeOAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthServer will
// result in compilation errors.
type UnsafeOAuthServer interface {
	mustEmbedUnimplementedOAuthServer()
}

func RegisterOAuthServer(s grpc.ServiceRegistrar, srv OAuthServer) {
	s.RegisterService(&OAuth_ServiceDesc, srv)
}

func _OAuth_RequestAccessTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationGrant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServer).RequestAccessTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OAuth.OAuth/RequestAccessTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServer).RequestAccessTokens(ctx, req.(*AuthorizationGrant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth_RefreshAccessTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServer).RefreshAccessTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OAuth.OAuth/RefreshAccessTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServer).RefreshAccessTokens(ctx, req.(*AccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth_InvalidateTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServer).InvalidateTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OAuth.OAuth/InvalidateTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServer).InvalidateTokens(ctx, req.(*LogoutToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth_OAuthTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServer).OAuthTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OAuth.OAuth/OAuthTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServer).OAuthTest(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth_PersistUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServer).PersistUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OAuth.OAuth/PersistUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServer).PersistUser(ctx, req.(*EmailCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth_CreateTempUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserForm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServer).CreateTempUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OAuth.OAuth/CreateTempUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServer).CreateTempUser(ctx, req.(*UserForm))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuth_ServiceDesc is the grpc.ServiceDesc for OAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OAuth.OAuth",
	HandlerType: (*OAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestAccessTokens",
			Handler:    _OAuth_RequestAccessTokens_Handler,
		},
		{
			MethodName: "RefreshAccessTokens",
			Handler:    _OAuth_RefreshAccessTokens_Handler,
		},
		{
			MethodName: "InvalidateTokens",
			Handler:    _OAuth_InvalidateTokens_Handler,
		},
		{
			MethodName: "OAuthTest",
			Handler:    _OAuth_OAuthTest_Handler,
		},
		{
			MethodName: "PersistUser",
			Handler:    _OAuth_PersistUser_Handler,
		},
		{
			MethodName: "CreateTempUser",
			Handler:    _OAuth_CreateTempUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "OAuth.proto",
}
